"""add is_quiz_buddy_original

Revision ID: 63c9c28540e1
Revises: fc728d1b3f41
Create Date: 2024-07-13 07:29:10.354089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63c9c28540e1'
down_revision = 'fc728d1b3f41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_quiz_buddy_original', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('is_quiz_buddy_original')

    # ### end Alembic commands ###
