"""Add user ip and is shared fields to Quiz

Revision ID: a6b226889e6f
Revises: 4ff1355b05c7
Create Date: 2024-07-09 09:05:55.057559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6b226889e6f'
down_revision = '4ff1355b05c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_ip', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('is_shared', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('is_shared')
        batch_op.drop_column('user_ip')

    # ### end Alembic commands ###
