"""update language column length

Revision ID: c5cb4c80859d
Revises: 63c9c28540e1
Create Date: 2024-07-16 07:39:39.299349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5cb4c80859d'
down_revision = '63c9c28540e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=7),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.alter_column('language',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=2),
               existing_nullable=False)

    # ### end Alembic commands ###
